#!/bin/sh
set -e

# Runs as root (see the Dockerfile — there's no USER app before this) so it
# can unconditionally fix ownership of every writable mount below, every
# boot — a named volume can end up root-owned (Docker only seeds a volume
# from the image's own content the very first time it's used; anything
# already existing in a wrong state is never retroactively fixed by that),
# and a bind-mounted host directory is owned by whatever uid created it on
# the host, almost never this container's `app` uid.
chown -R app:app /app/.secrets /app/public/uploads /app/logs /app/backups

SECRETS_DIR="/app/.secrets"
mkdir -p "$SECRETS_DIR"

# The Dockerfile bakes a session secret into the image at this same path at
# build time — fine for a plain named-volume deploy (Docker seeds a volume
# from the image's own content the first time it's used), but some hosting
# platforms mount an empty persistent disk here instead, silently shadowing
# whatever the image put at this path. So this can't just check for the
# file and skip if missing — it has to generate one itself the first time
# this directory turns out to be empty, and persist it, so every boot after
# the first reuses it.
if [ -z "$sessionSecret" ] && [ ! -f "$SECRETS_DIR/session-secret" ]; then
    node -e "require('fs').writeFileSync('$SECRETS_DIR/session-secret', require('crypto').randomBytes(64).toString('hex'))"
    chown app:app "$SECRETS_DIR/session-secret"
fi

# By this point session-secret is guaranteed to exist — either baked in by
# the Dockerfile, seeded from that by a Docker named volume on first use, or
# generated by this script above when neither of those applied. Only read it
# when nothing more specific was already set via the sessionSecret env var.
if [ -z "$sessionSecret" ] && [ -f "$SECRETS_DIR/session-secret" ]; then
    export sessionSecret="$(cat "$SECRETS_DIR/session-secret")"
fi

# Safe to run every boot — see services/bootstrap/createInitialAdmin.js's own
# comment; it no-ops once an admin already exists or ADMIN_EMAIL/ADMIN_PASSWORD
# aren't both set.
gosu app node scripts/bootstrapAdmin.js

# Drops from root to the unprivileged `app` user right here, for the actual
# long-running server process — gosu (not su/sudo) specifically because it
# execs directly rather than forking a subshell, so signals (SIGTERM on
# `docker stop`, etc.) and PID 1 reach the real node process correctly.
exec gosu app "$@"
