// Handles what scripts/setup-wizard.js (and scripts/update.js) do once .env
// is written and the app itself has been (or is about to be) brought up:
// builds a stably-tagged local image (this project always builds locally,
// never pulls a published one — see the README's "Why build locally instead
// of pulling an image?"), writes a small self-contained docker-compose.yml
// (no build context, so it works with no source present), copies
// nginx/nginx.conf.template and update.sh alongside it, brings the trimmed
// stack up from finalDir, then deletes the scratch checkout — .env/certs/
// are written directly to finalDir by the wizard already (see
// scripts/setup-wizard.js), so there's nothing to carry over for those.
const fs = require('fs');
const path = require('path');
const { printAccessUrls } = require('./network');
const { run, ensureDockerInstalled, writeDeployState } = require('./bringUp');

const LOCAL_BUILD_TAG = 'balancedwaypoints-app:local';

// Always includes the nginx service — unlike fondwaypoints, this project's
// host-nginx wiring (scripts/lib/bringUp.js's installHostNginxSite) sits IN
// FRONT of the bundled nginx sidecar over loopback HTTPS rather than
// replacing it (see that function's own doc comment for why), so there's no
// "omit the sidecar" branch to make here.
function buildMinimalComposeYaml({ mongoMode, appImage, nginxHttpsPort, nginxHttpPort }) {
    const volumes = ['logs-data', 'backups-data'];
    let app = `  app:
    image: ${appImage}
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - \${LOGS_HOST_DIR:-logs-data}:/app/logs
      - \${BACKUP_HOST_DIR:-backups-data}:/app/backups`;
    if (mongoMode === 'internal') {
        app += `
    depends_on:
      mongo:
        condition: service_healthy`;
    }

    const nginx = `

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - app
    env_file:
      - .env
    ports:
      - "${nginxHttpPort}:80"
      - "${nginxHttpsPort}:${nginxHttpsPort}"
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/templates/default.conf.template:ro
      - \${SSL_CERT_FILE:-./certs/cert.pem}:/etc/nginx/certs/server.pem:ro
      - \${SSL_KEY_FILE:-./certs/cert.key}:/etc/nginx/certs/server.key:ro`;

    let mongo = '';
    if (mongoMode === 'internal') {
        volumes.push('mongo-data');
        mongo = `

  mongo:
    image: \${MONGO_IMAGE:-mongo:7}
    restart: unless-stopped
    volumes:
      - \${MONGO_HOST_DIR:-mongo-data}:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval \\"db.adminCommand('ping')\\" || mongo --quiet --eval \\"db.adminCommand('ping')\\""]
      interval: 5s
      timeout: 5s
      retries: 20`;
    }

    const volumesBlock = volumes.map(v => `  ${v}:`).join('\n');

    return `# Generated by the "Docker only, minimal footprint" install/update — a
# self-contained compose file with no build context, since the source
# checkout that built the image is deleted once this stack is up.
# Regenerated on every update.sh run to pick up upstream compose changes;
# hand edits here will be overwritten by the next update.
services:
${app}${nginx}${mongo}

volumes:
${volumesBlock}
`;
}

// Builds the app image (tagged so it survives the scratch checkout being
// deleted), writes the trimmed compose file, copies update.sh/nginx's
// template, brings the stack up from finalDir, then deletes scratchDir.
// .env/certs/ are already at finalDir (written there directly by the
// wizard), so this only ever touches the Docker-runtime side of things.
function trimToMinimalFootprint(scratchDir, finalDir, opts) {
    const { mongoMode, nginxHttpsPort, nginxHttpPort, installedVersion } = opts;

    if (!ensureDockerInstalled()) {
        console.error('\nInstall Docker manually, then re-run this install to bring the minimal-footprint stack up.');
        process.exit(1);
    }

    console.log(`\n== Building ${LOCAL_BUILD_TAG} from ${scratchDir} ==`);
    if (!run('docker', ['build', '-t', LOCAL_BUILD_TAG, '.'], { cwd: scratchDir })) {
        console.error('\ndocker build failed — see output above.');
        process.exit(1);
    }

    fs.mkdirSync(finalDir, { recursive: true });
    fs.writeFileSync(
        path.join(finalDir, 'docker-compose.yml'),
        buildMinimalComposeYaml({ mongoMode, appImage: LOCAL_BUILD_TAG, nginxHttpsPort, nginxHttpPort })
    );

    fs.mkdirSync(path.join(finalDir, 'nginx'), { recursive: true });
    fs.copyFileSync(
        path.join(scratchDir, 'nginx', 'nginx.conf.template'),
        path.join(finalDir, 'nginx', 'nginx.conf.template')
    );

    fs.copyFileSync(path.join(scratchDir, 'update.sh'), path.join(finalDir, 'update.sh'));
    fs.chmodSync(path.join(finalDir, 'update.sh'), 0o755);

    writeDeployState(finalDir, { footprint: 'minimal', mongoMode, installedVersion });

    console.log(`\n== Bringing up the minimal Docker stack from ${finalDir} ==`);
    if (!run('docker', ['compose', 'up', '-d'], { cwd: finalDir })) {
        console.error('\ndocker compose up failed — see output above.');
        process.exit(1);
    }
    console.log(`\nDone. Check status with: cd ${finalDir} && docker compose ps`);

    console.log(`\n== Removing the scratch checkout at ${scratchDir} ==`);
    if (!run('rm', ['-rf', scratchDir])) {
        console.error(`Failed to remove ${scratchDir} — the app is up, but that directory is safe to delete by hand whenever convenient.`);
    }

    let webFqdn = 'localhost';
    try {
        const envText = fs.readFileSync(path.join(finalDir, '.env'), 'utf8');
        const match = envText.match(/^WEB_FQDN=(.*)$/m);
        if (match) webFqdn = match[1];
    } catch { /* fall back to localhost */ }
    printAccessUrls(webFqdn, nginxHttpsPort);
}

module.exports = { trimToMinimalFootprint };
