const mongoose = require('mongoose');

const FREQUENCY_UNITS = ['days', 'weeks', 'months', 'years'];

const splitSchema = new mongoose.Schema({
    category: { type: mongoose.Schema.Types.ObjectId, ref: 'Category', required: true },
    amountCents: { type: Number, required: true },
    notes: { type: String, trim: true, default: '' }
}, { _id: false });

// A full-snapshot override of one or more upcoming occurrences, without
// touching the base schedule's own fields (which apply to every occurrence
// before, and every occurrence after, whatever range these override) — see
// services/schedules/occurrenceOverrides.js for how these ranges are kept
// non-overlapping as new edits come in.
const occurrenceOverrideSchema = new mongoose.Schema({
    // The first occurrence date (as generated by nextOccurrence stepping
    // from the schedule's own nextDate) this override applies to.
    occurrenceDate: { type: Date, required: true },
    // Total occurrences this override covers, starting at occurrenceDate
    // (1 = just that one) — null means "this occurrence and every one
    // after it, forever".
    occurrenceCount: { type: Number, default: null },
    // true = these occurrences are permanently deleted — never posted,
    // never shown as upcoming again. The fields below are unused when true.
    skip: { type: Boolean, default: false },
    amountCents: { type: Number, default: null },
    category: { type: mongoose.Schema.Types.ObjectId, ref: 'Category', default: null },
    payee: { type: mongoose.Schema.Types.ObjectId, ref: 'Payee', default: null },
    notes: { type: String, trim: true, default: '' },
    splits: { type: [splitSchema], default: [] }
});

const scheduleSchema = new mongoose.Schema({
    owner: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    name: { type: String, required: true, trim: true },
    account: { type: mongoose.Schema.Types.ObjectId, ref: 'Account', required: true },
    payee: { type: mongoose.Schema.Types.ObjectId, ref: 'Payee', default: null },
    amountCents: { type: Number, required: true },
    category: { type: mongoose.Schema.Types.ObjectId, ref: 'Category', default: null },
    splits: { type: [splitSchema], default: [] },
    frequency: {
        unit: { type: String, enum: FREQUENCY_UNITS, default: 'months' },
        interval: { type: Number, default: 1, min: 1 }
    },
    nextDate: { type: Date, required: true },
    endDate: { type: Date, default: null },
    // Auto-entered schedules post a real Transaction the day they're due
    // (services/schedules/scheduler.js). Non-auto-entered ones only ever
    // surface as an "upcoming" reminder computed on the fly.
    autoEnter: { type: Boolean, default: false },
    reminderDaysBefore: { type: Number, default: 3, min: 0 },
    active: { type: Boolean, default: true },
    notes: { type: String, trim: true, default: '' },
    // Per-schedule opt-in — when true, everyone with their own SMTP
    // configured (see models/user.js's smtp field) gets emailed once this
    // occurrence enters its reminder window (see
    // services/jobs/scheduleReminderEmailJob.js).
    notifyByEmail: { type: Boolean, default: false },
    // Dedup marker: the nextDate value a reminder was last sent for, so the
    // same occurrence doesn't re-email every day it sits inside the
    // reminder window. Compared against nextDate, which only changes when a
    // schedule actually advances (auto-enter, or a manual edit).
    lastNotifiedForDate: { type: Date, default: null },
    // Per-occurrence edits — see services/schedules/occurrenceOverrides.js.
    occurrenceOverrides: { type: [occurrenceOverrideSchema], default: [] }
}, { timestamps: true });

scheduleSchema.index({ owner: 1, nextDate: 1 });

module.exports = mongoose.model('Schedule', scheduleSchema);
module.exports.FREQUENCY_UNITS = FREQUENCY_UNITS;
