const mongoose = require('mongoose');

const FREQUENCY_UNITS = ['days', 'weeks', 'months', 'years'];

const splitSchema = new mongoose.Schema({
    category: { type: mongoose.Schema.Types.ObjectId, ref: 'Category', required: true },
    amountCents: { type: Number, required: true },
    notes: { type: String, trim: true, default: '' }
}, { _id: false });

// A full-snapshot override of one or more upcoming occurrences, without
// touching the base schedule's own fields (which apply to every occurrence
// before, and every occurrence after, whatever range these override) — see
// services/schedules/occurrenceOverrides.js for how these ranges are kept
// non-overlapping as new edits come in.
const occurrenceOverrideSchema = new mongoose.Schema({
    // The first occurrence date (as generated by nextOccurrence stepping
    // from the schedule's own nextDate) this override applies to.
    occurrenceDate: { type: Date, required: true },
    // Total occurrences this override covers, starting at occurrenceDate
    // (1 = just that one) — null means "this occurrence and every one
    // after it, forever".
    occurrenceCount: { type: Number, default: null },
    // true = these occurrences are permanently deleted — never posted,
    // never shown as upcoming again. The fields below are unused when true.
    skip: { type: Boolean, default: false },
    amountCents: { type: Number, default: null },
    category: { type: mongoose.Schema.Types.ObjectId, ref: 'Category', default: null },
    payee: { type: mongoose.Schema.Types.ObjectId, ref: 'Payee', default: null },
    notes: { type: String, trim: true, default: '' },
    splits: { type: [splitSchema], default: [] }
});

const scheduleSchema = new mongoose.Schema({
    owner: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    name: { type: String, required: true, trim: true },
    account: { type: mongoose.Schema.Types.ObjectId, ref: 'Account', required: true },
    payee: { type: mongoose.Schema.Types.ObjectId, ref: 'Payee', default: null },
    amountCents: { type: Number, required: true },
    category: { type: mongoose.Schema.Types.ObjectId, ref: 'Category', default: null },
    splits: { type: [splitSchema], default: [] },
    // When set, this schedule posts a transfer (see
    // services/database/transactions.js's createTransfer) between `account`
    // and this one instead of a plain categorized transaction — mirrors the
    // register's own "this is a transfer" toggle. Mutually exclusive with
    // payee/category/splits, same convention as models/transaction.js's own
    // transferAccount field; controllers/schedulesController.js enforces
    // that rather than the schema, matching how Transaction does it too.
    transferAccount: { type: mongoose.Schema.Types.ObjectId, ref: 'Account', default: null },
    // Purely a register/UI label meaning "this bill is paid automatically
    // by the biller" — unrelated to autoEnter below, which controls whether
    // THIS APP posts the transaction on its own vs. leaving it as a manual
    // reminder. Independent of transferAccount, too: a recurring transfer
    // can be autopay-flagged as well (e.g. an automatic draft to savings).
    autopay: { type: Boolean, default: false },
    // Optional — the account autopay actually drafts from, when it differs
    // from `account` (e.g. a credit card bill (account) auto-paid out of
    // checking (autopayFromAccount)). Mutually exclusive with
    // transferAccount, which already fully describes both sides of the
    // money movement for a transfer schedule; controllers/schedulesController.js
    // enforces that rather than the schema, same convention as
    // transferAccount's own comment above. When set, posting an occurrence
    // creates a linked pair (see services/database/transactions.js's
    // createAutopayOccurrence) instead of a single categorized transaction.
    autopayFromAccount: { type: mongoose.Schema.Types.ObjectId, ref: 'Account', default: null },
    // 'interval' (default — every schedule from before ordinal-weekday
    // recurrence existed) uses unit/interval below. 'ordinalWeekday' uses
    // weekday/ordinals instead — unit/interval are left at their defaults
    // and simply unused, rather than making them conditionally required,
    // since services/schedules/nextOccurrence.js (the only code that reads
    // this object) dispatches on `kind` and ignores whichever pair doesn't
    // apply.
    frequency: {
        kind: { type: String, enum: ['interval', 'ordinalWeekday'], default: 'interval' },
        unit: { type: String, enum: FREQUENCY_UNITS, default: 'months' },
        interval: { type: Number, default: 1, min: 1 },
        // Only meaningful when kind is 'ordinalWeekday' — 0 (Sunday)
        // through 6 (Saturday), matching Date#getUTCDay's convention.
        weekday: { type: Number, min: 0, max: 6, default: null },
        // Only meaningful when kind is 'ordinalWeekday' — which
        // occurrence(s) of that weekday within the month to recur on: 1-4
        // for 1st..4th, -1 for "last" (whichever ordinal that turns out to
        // be that month). Multiple values recur on all of them at once —
        // e.g. [2, -1] is "the 2nd and last Wednesday of every month".
        ordinals: { type: [Number], default: [] }
    },
    nextDate: { type: Date, required: true },
    endDate: { type: Date, default: null },
    // Auto-entered schedules post a real Transaction the day they're due
    // (services/schedules/scheduler.js). Non-auto-entered ones only ever
    // surface as an "upcoming" reminder computed on the fly.
    autoEnter: { type: Boolean, default: false },
    reminderDaysBefore: { type: Number, default: 3, min: 0 },
    active: { type: Boolean, default: true },
    notes: { type: String, trim: true, default: '' },
    // Per-schedule opt-in — when true, everyone with their own SMTP
    // configured (see models/user.js's smtp field) gets emailed once this
    // occurrence enters its reminder window (see
    // services/jobs/scheduleReminderEmailJob.js).
    notifyByEmail: { type: Boolean, default: false },
    // Dedup marker: the nextDate value a reminder was last sent for, so the
    // same occurrence doesn't re-email every day it sits inside the
    // reminder window. Compared against nextDate, which only changes when a
    // schedule actually advances (auto-enter, or a manual edit).
    lastNotifiedForDate: { type: Date, default: null },
    // Per-occurrence edits — see services/schedules/occurrenceOverrides.js.
    occurrenceOverrides: { type: [occurrenceOverrideSchema], default: [] }
}, { timestamps: true });

scheduleSchema.index({ owner: 1, nextDate: 1 });

module.exports = mongoose.model('Schedule', scheduleSchema);
module.exports.FREQUENCY_UNITS = FREQUENCY_UNITS;
